language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-frontend thachnamtrang/udagram-frontend:latest
  - docker tag reverseproxy thachnamtrang/reverseproxy:latest
  - docker tag udagram-api-user thachnamtrang/udagram-api-user:latest
  - docker tag udagram-api-feed thachnamtrang/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thachnamtrang/udagram-frontend
  - docker push thachnamtrang/reverseproxy
  - docker push thachnamtrang/udagram-api-user
  - docker push thachnamtrang/udagram-api-feed
